### ISSUE TITLE
Error while using OpenCV

### ISSUE THREAD

**Issue by karanaggarwal1994** [maxruby/OpenCV.jl#13]
julia> using OpenCV
ERROR: LoadError: LoadError: LoadError: could not open file /home/karan/.julia/v0.5/Cxx/src/../deps/build/clang_constants.jl
 in include_from_node1(::String) at ./loading.jl:488 (repeats 3 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
 in include_from_node1(::String) at ./loading.jl:488
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
while loading /home/karan/.julia/v0.5/Cxx/src/typetranslation.jl, in expression starting on line 433
while loading /home/karan/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 158
while loading /home/karan/.julia/v0.5/OpenCV/src/OpenCV.jl, in expression starting on line 27

**Comment by maxruby** [comment]
From the snippet you sent, it seems there is an issue with `Cxx.jl` support for the latest state of `OpenCV.jl`. 
```
while loading /home/karan/.julia/v0.5/Cxx/src/typetranslation.jl, in expression starting on line 433
while loading /home/karan/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 158
```
Unfortunately, I have not used julia v0.5 so I cannot help you right now.  Does your `Cxx.jl`installation alone work well with julia v0.5?

**Comment by maxruby** [comment]
This issue is not likely related to `OpenCV.jl` itself.  I can confirm that with the latest julia `0.6.0-pre.alpha.49`, commit `eca966c` this error can not be reproduced (MacOS 10.12.3).  Please try `0.6.0-pre.alpha.49` and if the same issue comes up, report it here again.
