### ISSUE TITLE
General Issue Request

### ISSUE THREAD

**Issue by siddhantjain** [maxruby/OpenCV.jl#2]
Could you please point me to something specific to work on in completing the thin wrappers for OpenCV modules?

**Comment by maxruby** [comment]
Happy new year to you.
Have you managed to install 0.4.0-dev?

**Comment by maxruby** [comment]
Sorry, did not mean to close it.

**Comment by maxruby** [comment]
@siddhantjain.  I will continue wrapping the remaining modules this weekend.

**Comment by siddhantjain** [comment]
Please continue wrapping and not let me turtle speed hinder with your
progress. I got caught up in some unexpected string of work, I should sit
once and set up the environment this weekend.



On Wed, Jan 14, 2015 at 1:36 AM, Maximiliano Suster <
notifications@github.com> wrote:

> @siddhantjain <https://github.com/siddhantjain>. I will continue wrapping
> the remaining modules this weekend.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/maxruby/OpenCV.jl/issues/2#issuecomment-69810172>.
>



-- 
"what you do speaks so loudly that i cant hear what you say"
