### ISSUE TITLE
ReadOnlyMemoryError() on running "using OpenCV" in ubuntu 14.04

### ISSUE THREAD

**Issue by vernwalrahul** [maxruby/OpenCV.jl#32]
![screenshot from 2017-03-25 19 10 33](https://cloud.githubusercontent.com/assets/23414388/24322664/de711c4c-118e-11e7-854f-e7f1cf6abec3.png)

**Comment by maxruby** [comment]
Please see #17.  This is likely related to OpenCV installation issues.

**Comment by kvmanohar22** [comment]
@vernwalrahul  Have you commented out the #include statements from for `flann` in `opencv.hpp` ?

**Comment by vernwalrahul** [comment]
Thanks.  Actually, it had two versions of opencv.
