### ISSUE TITLE
pkg-config changes in OpenCV-3.0.0

### ISSUE THREAD

**Issue by andrewadare** [maxruby/OpenCV.jl#7]
This is a small issue, but maybe still worth mentioning.

I installed the new OpenCV 3.0.0 "gold" release yesterday, and it looks like the output of pkg-config is a little different than before (at least for me on OS X). It looks like this:

```
$ pkg-config --libs opencv
-L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_viz -lopencv_core -lopencv_hal
```

I had to remove the trailing slash on `/usr/local/lib/` in OpenCV.jl, and I also changed `match(Regex("$(i[1:end-6])")` to `match(Regex("$(i[4:end-6])")` so that the "lib" part of the string is not required for a match. I don't think either of these changes would prevent this package from working with the older OpenCV 3 beta releases.

**Comment by maxruby** [comment]
Great.   Should we add all the modifications you made so far to get `OpenCV.jl` to work to the `README`? If you make a PR with the proposed changes, I will look at it asap. Thanks.
Cheers,
Max
