### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by elsuizo** [maxruby/OpenCV.jl#8]
Hi first thanks for do it this amazing Pkg
I installed  opencv3.0 in a Debian Jessie and i have julia-0.4-dev. and this error:

``` julia
julia> using OpenCV
libopencv_viz.3.0.0 is not found in pkg-config
ERROR: LoadError: No pre-installed libraries. Set path manually or install OpenCV.
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /home/elsuizo/.julia/v0.4/OpenCV/src/OpenCV.jl, in expression starting on line 63
```

the `pkg-config --libs opencv` output is fine(i think)

``` bash
-L/usr/local/lib -lopencv_shape -lopencv_stitching -lopencv_objdetect -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal
```

I miss something?¿?

**Comment by maxruby** [comment]
I think I know what the problem is - I will try to look at it tonight.
Am 10.07.2015 17:50 schrieb "Martín Noblía" <notifications@github.com>:

**Comment by maxruby** [comment]
This is likely due to the the naming of the OpenCV libs in `src/OpenCV.jl`which needs to be customized for Linux (from the default OSX) as reported in #7.
Did you try 
- removing the trailing slash in `/usr/local/lib/`
- changing `match(Regex("$(i[1:end-6])")` to `match(Regex("$(i[4:end-6])")` in `src/OpenCV.jl`

**Comment by elsuizo** [comment]
the error is fine, due i not installed with VTK support, i will install VTK and report you the results. Thanks for your time
