### ISSUE TITLE
Remove binaries - rebase master

### ISSUE THREAD

**Issue by stemann** [maxruby/OpenCV.jl#9]
Hi,

First and foremost: Impressive work done on this package.

I would like to suggest that the OS X binaries are replaced by a generic deps/build.jl script using BinDeps to provide binaries -- by rebasing master onto the second commit, i.e. the second commit generated by Pkg.generate("OpenCV", ...).

I would be happy to help.

Best regards,
Jesper

**Comment by maxruby** [comment]
Hi Jesper, 

Glad that you find the package useful.  I am happy to accept a PR with your suggested revisions.
I can also give you push access if necessary.  I agree that it would be nice to have a more general approach to load the binaries into `OpenCV.jl`.

Cheers,
Max

**Comment by maxruby** [comment]
Building binaries with binDeps would be a good idea in the future, but given the range of dependencies of OpenCV and OS requirements, this will need to be more time-consuming than can be justified right now.
